#ifndef BATTLESHIP_H  //Generated by QT, didn't bother changeing to #pragma once
#define BATTLESHIP_H
#include "player.h"

class battleship : public player {
private:
    bool* flagSpecialPowerOn;
    int* originalShields;
    int* originalMaxShields;
    int* originalWeaponPower;
public:
    battleship();
    ~battleship();
    void specialPowerOn();
    void specialPowerOff();
};

#endif // BATTLESHIP_H
